### ISSUE TITLE
Error deploying java app to Elastic Beanstalk

### ISSUE THREAD

**Issue by Psep** [aws-samples/devsecops-cicd#13]
When I executed pipeline I had a error with deploy java app:

![imagen](https://user-images.githubusercontent.com/392854/224515212-f7fddc3a-145d-433e-89dd-e8932417630d.png)

I checked the beanstalk log (eb-engine.log) and I found this error:

![imagen](https://user-images.githubusercontent.com/392854/224515257-117d589a-6522-4535-95c8-780c540f8df0.png)

These configuration was added in last commit https://github.com/aws-samples/devsecops-cicd/commit/d5e85bd1ea2edad6e5573c3bcbae9fd7ca2f84c1. It seems that "server_tokens" setting already exists in the initial NGINX setup in Beanstalk so there is no need to add this again. I removed this from custom.conf file in my project and this worked for me.

**Comment by aminaabsar** [comment]
Were you able to resolve the issue ? I am facing the same issue.

**Comment by Psep** [comment]
> Were you able to resolve the issue ? I am facing the same issue.
> 

Yes. I did it.

Delete "server_tokens" line from your custom.conf file.
